[package]
name = "mytrait-derive"
version = "0.1.0"
authors = ["imbolc <me@imbolc.name>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.13"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
